version: "2"

linters:
  default: none
  enable:
    - logmsglint
  settings:
    custom:
      logmsglint:
        type: module
        description: checks log messages for style and secrets
        settings:
          check-lowercase: true
          check-english-only: true
          check-special-symbols: true
          check-sensitive-data: true
          allow-dash: true
          sensitive-keywords:
            - password
            - token
            - secret
            - api_key